Bug fixes to User.update()
Apt-Get-SWE/SWEProject-Aptget pull request #103
Opened 2023-02-23 20:36 UTC by TomY-Zhang

2023-02-23 20:46 UTC, leo4life2 submitted a review, later dismissed

2023-02-24 18:51 UTC, Olivernyu commented on server/src/types/address.py
> +                raise errors.DuplicateKeyError(f'Address with address id {data["aid"]} already exists')
Why are we raising an error? If two separate users try to insert the same address then the later one will see an error. Same comment for other two types. For login specifically, if someone tries to do login twice in a role, do they see an error? 
I think there are several approaches we can take, either do checks before insert() is called, or modify this function to do nothing when an entry already exists. Either way, I think the schema here needs to be more explicitly considered and documented so we don't have bugs later on.

2023-02-24 18:57 UTC, Olivernyu requested changes
I think we need to think more carefully on what to do when an insert happens with an already existing entry in our db. Raising an error for what the user will perceive and expect as a normal interaction does not seem appropriate.

2023-02-24 19:02 UTC, TomY-Zhang commented on server/src/types/address.py
> +                raise errors.DuplicateKeyError(f'Address with address id {data["aid"]} already exists')
I raised an error simply to log the error, but I agree with your point. I'll make changes to remove the error raising and include the update() function.

2023-02-26 21:59 UTC, Olivernyu approved these changes
lgtm

2023-02-26 22:03 UTC, merged