Added methods for finding objects in db
Apt-Get-SWE/SWEProject-Aptget pull request #17
Opened 2022-10-14 19:12 UTC by TomY-Zhang

2022-10-15 18:22 UTC, Alex-YuYan approved these changes

2022-10-16 17:47 UTC, Olivernyu approved these changes
LGTM

2022-10-16 17:55 UTC, leo4life2 requested changes

2022-10-16 17:55 UTC, leo4life2 commented on server/src/types/types.py
> +
why do we need this here lol? the one in query has filters={} by default as well so we could use that

2022-10-16 17:55 UTC, leo4life2 approved these changes
nevermind lol, just saw that you put the constant inside.

2022-10-16 22:25 UTC, merged